# Docker Compose для Development с hot reload
version: '3.8'

services:
  frontend:
    build:
      context: ./ai-chat-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
    # Volume mapping для быстрого обновления без пересборки
    volumes:
      - ./ai-chat-frontend/dist:/usr/share/nginx/html:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider http://localhost/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s