# AI Chat Frontend CI/CD Pipeline
name: CI/CD Pipeline

on:
  push:
    branches: [main, develop]
    paths:
      - 'ai-chat-frontend/**'
      - '.github/workflows/**'
  pull_request:
    branches: [main]
    paths:
      - 'ai-chat-frontend/**'
  workflow_dispatch: # Ручной запуск

# Глобальные переменные для всех jobs
env:
  NODE_VERSION: '18'
  WORKING_DIRECTORY: './ai-chat-frontend'

jobs:
  # =====================================
  # Проверка качества кода
  # =====================================
  quality-check:
    name: 🔍 Code Quality
    runs-on: ubuntu-latest
    
    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v4
      
      - name: 📦 Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: '${{ env.WORKING_DIRECTORY }}/package-lock.json'
      
      - name: 🔧 Install dependencies
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: npm ci --prefer-offline --no-audit
      
      - name: 📝 Run type check
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: npm run type-check
      
      - name: 🧹 Run linting
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: npm run lint
      
      - name: 💅 Check formatting
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: npm run format:check

  # =====================================
  # Тестирование
  # =====================================
  test:
    name: 🧪 Tests
    runs-on: ubuntu-latest
    
    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v4
      
      - name: 📦 Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: '${{ env.WORKING_DIRECTORY }}/package-lock.json'
      
      - name: 🔧 Install dependencies
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: npm ci --prefer-offline --no-audit
      
      - name: 🧪 Run unit tests
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: npm run test:ci
      
      - name: 📊 Upload coverage to Codecov
        if: success()
        uses: codecov/codecov-action@v3
        with:
          working-directory: ${{ env.WORKING_DIRECTORY }}
          files: ./coverage/lcov.info
          flags: frontend
          name: ai-chat-frontend
          fail_ci_if_error: false

  # =====================================
  # Сборка приложения
  # =====================================
  build:
    name: 🏗️ Build
    needs: [quality-check, test]
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        environment: [staging, production]
    
    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v4
      
      - name: 📦 Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: '${{ env.WORKING_DIRECTORY }}/package-lock.json'
      
      - name: 🔧 Install dependencies
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: npm ci --prefer-offline --no-audit
      
      - name: 🏗️ Build application (${{ matrix.environment }})
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: npm run build
        env:
          NODE_ENV: production
          VITE_API_URL: ${{ matrix.environment == 'production' && secrets.PROD_API_URL || secrets.STAGING_API_URL }}
          VITE_WS_URL: ${{ matrix.environment == 'production' && secrets.PROD_WS_URL || secrets.STAGING_WS_URL }}
          VITE_APP_ENV: ${{ matrix.environment }}
      
      - name: 📦 Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-${{ matrix.environment }}
          path: ${{ env.WORKING_DIRECTORY }}/dist/
          retention-days: 7
          compression-level: 6

  # =====================================
  # Docker сборка и тестирование
  # =====================================
  docker-build:
    name: 🐳 Docker Build
    needs: [quality-check, test]
    runs-on: ubuntu-latest
    
    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v4
      
      - name: 🐳 Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: 🔑 Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: 🏷️ Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/ai-chat-frontend
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=sha,prefix={{branch}}-
            type=raw,value=latest,enable={{is_default_branch}}
      
      - name: 🏗️ Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ${{ env.WORKING_DIRECTORY }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64,linux/arm64

  # =====================================
  # Deployment (только для main branch)
  # =====================================
  deploy-staging:
    name: 🚀 Deploy to Staging
    needs: [build, docker-build]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop'
    environment:
      name: staging
      url: https://staging-ai-chat.vercel.app
    
    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v4
      
      - name: 📦 Download build artifacts
        uses: actions/download-artifact@v5
        with:
          name: dist-staging
          path: ${{ env.WORKING_DIRECTORY }}/dist
      
      - name: 🚀 Deploy to Vercel (Staging)
        uses: vercel/action@v1
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_STAGING_PROJECT_ID }}
          working-directory: ${{ env.WORKING_DIRECTORY }}
          vercel-args: '--prebuilt'
        env:
          VERCEL_PROJECT_SETTINGS: './vercel.staging.json'

  deploy-production:
    name: 🎉 Deploy to Production
    needs: [build, docker-build]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    environment:
      name: production
      url: https://ai-chat.vercel.app
    
    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v4
      
      - name: 📦 Download build artifacts
        uses: actions/download-artifact@v5
        with:
          name: dist-production
          path: ${{ env.WORKING_DIRECTORY }}/dist
      
      - name: 🚀 Deploy to Vercel (Production)
        uses: vercel/action@v1
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PRODUCTION_PROJECT_ID }}
          working-directory: ${{ env.WORKING_DIRECTORY }}
          vercel-args: '--prebuilt --prod'
      
      - name: 📋 Create GitHub Release
        if: success()
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.run_number }}
          release_name: Release v${{ github.run_number }}
          body: |
            🚀 **Production Deployment**
            
            **Changes:** 
            - Commit: ${{ github.sha }}
            - Branch: ${{ github.ref_name }}
            
            **Deployed to:** https://ai-chat.vercel.app
            
            **Docker Image:** `${{ secrets.DOCKERHUB_USERNAME }}/ai-chat-frontend:${{ github.ref_name }}-${{ github.sha }}`
          draft: false
          prerelease: false

  # =====================================
  # Уведомления
  # =====================================
  notify:
    name: 📢 Notifications
    needs: [deploy-staging, deploy-production]
    runs-on: ubuntu-latest
    if: always()
    
    steps:
      - name: 📧 Notify on Slack
        if: failure()
        uses: 8398a7/action-slack@v3
        with:
          status: failure
          webhook_url: ${{ secrets.SLACK_WEBHOOK }}
          text: |
            🚨 **AI Chat Frontend CI/CD Failed**
            
            **Branch:** ${{ github.ref_name }}
            **Commit:** ${{ github.sha }}
            **Actor:** ${{ github.actor }}
            
            [View Workflow](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}